### ISSUE TITLE
ffmpeg-gst-wrapper 0.3.1: tests failing with `--no-default-features`

### ISSUE THREAD

**Issue by tenzap** [Farmadupe/vid_dup_finder_lib#24]
I started packaging ffmpeg-gst-wrapper 0.3.1 for Debian and while running the test suite I face these errors.

Commands that make it fail:
```
cargo test --all-targets --no-default-features --features glib
cargo test --all-targets --no-default-features --features ffmpeg_cmdline_utils
cargo test --all-targets --no-default-features --features
```

Output:
```
error[E0277]: `()` is not an iterator
   --> src/lib.rs:259:32
    |
259 |     pub fn spawn_gray(self) -> impl Iterator<Item = Result<GrayImage, FrameReadCfgErr>> {
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `()`

error[E0277]: `()` is not an iterator
   --> src/lib.rs:269:31
    |
269 |     pub fn spawn_rgb(self) -> impl Iterator<Item = Result<RgbImage, FrameReadCfgErr>> {
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `()`

error[E0308]: mismatched types
  --> src/lib.rs:61:43
   |
61 | pub fn get_resolution(src_path: &Path) -> Result<(u32, u32), FrameReadCfgErr> {
   |        --------------                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<(u32, u32), FrameReadCfgErr>`, found `()`
   |        |
   |        implicitly returns `()` as its body has no tail or `return` expression
   |
   = note:   expected enum `Result<(u32, u32), FrameReadCfgErr>`
           found unit type `()`

error[E0308]: mismatched types
  --> src/lib.rs:71:41
   |
71 | pub fn get_duration(src_path: &Path) -> Result<Duration, FrameReadCfgErr> {
   |        ------------                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<Duration, FrameReadCfgErr>`, found `()`
   |        |
   |        implicitly returns `()` as its body has no tail or `return` expression
   |
   = note:   expected enum `Result<Duration, FrameReadCfgErr>`
           found unit type `()`

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ffmpeg_gst_wrapper` (lib test) due to 4 previous errors
```

**Comment by Farmadupe** [comment]
This crate is an adapter for streaming video frames using either GStreamer or FFmpeg.

My intention is that the consumer must select at least one feature from "ffmpeg_backend" or "gstreamer_backend".

I'm not sure if this is the best API design though, as no-default-features causes a compile error.

Perhaps it would be better to always have the ffmpeg backend (This does not link to libffmpeg but instead invokes ffmpeg binary), and then leave "gstreamer_backend" if linking to libgstreamer is desired?

I'm happy to make any change to help you.

**Comment by tenzap** [comment]
Always the ffmpeg backend was the way it worked in v0.1? Actually in the Debian package I removed the gstreamer_backend feature because it pulls in multiple new dependencies that are not required by any package in Debian yet. The only software that requires vid_dup_finder_lib is and which is in Debian is czkzwka. And if doesn't require the gstreamer_backend feature.
So IIUC always having ffmpeg_backend (even when 'no default feature' is set) could work.

**Comment by Farmadupe** [comment]
Should now be fixed, updated versions of crates are published.

**Comment by tenzap** [comment]
lgtm, thanks.
